### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Samsterminator** [sedlak477/fusioncrafter#1]
I am trying to use this to craft Wyvern Cores and when even I put all the items in the input area it moves the emerald to the correct place, then comes up with this error: https://i.imgur.com/vECUNYY.png

I'm using All the Mods 3 Remix 1.5.4 and the default atm3r-config.

**Comment by sedlak477** [comment]
I'm very sorry for the late reply, I wasn't very active on GitHub and just saw it today. :sweat:  
This answer will probably be too late for you, but I'll try to clarify anyway so future people maybe can get some information if they encounter the same issue.

I tried to craft a Wyvern Core on my setup and it worked, so sadly I can't reproduce it...

But I've got some suggestions for things to try:
 * Check your sides in the config, maybe you have a typo or mixed some sides up
 * Try adding more memory to the machine (this requires an upgrade to a Tier 2 or 3 case :/) 
 * If you use some modded inventories try it with vanilla chests maybe OpenComputers just doesn't like the inventory

> Memory is modpack and even server specific so maybe your server has stricter memory budgets than the default values or you can try changing the OpenComputers config to allow for more memory on Tier 1 machines. You can get more info on the [official OpenComputers website](https://ocdoc.cil.li/#resource_limits).

If the suggestions don't resolve the issue, please post some more info about your setup and use a bigger screen that can display the whole error message (requires upgrade to Tier 2/3 Case, Screen and Graphics Card).

Again I apologise for the very unhelpful late reply, but I hope it helps. :disappointed:

**Comment by Samsterminator** [comment]
I fixed this quite a while ago, but I believe it was because I had the outputs mistaken, if I recall correctly I mixed up result and output.
